version: '3.3'

services:
  backend:
    image: b10nicle/kittygram_backend:latest
    container_name: backend
    volumes:
      - backend_media:/app/media
      - backend_static:/app/collected_static
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always
    networks:
      - default

  frontend:
    image: b10nicle/kittygram_frontend:latest
    container_name: frontend
    ports:
      - "3000:8000"
    volumes:
      - frontend_static:/app/build
    depends_on:
      - backend
    restart: always
    networks:
      - default

  gateway:
    image: b10nicle/kittygram_gateway:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - frontend_static:/var/html/static
      - backend_static:/var/html/backend
      - media:/var/html/media
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - default

  postgres:
    image: postgres:13.10
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - default

volumes:
  frontend_static:
  backend_static:
  media:
  pg_data:
