version: '3.3'

services:
  backend:
    image: b10nicle/kittygram_backend:latest
    platform: linux/amd64
    container_name: backend
    volumes:
      - media:/app/media
      - backend_static:/backend_static
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always
    networks:
      - default

  frontend:
    image: b10nicle/kittygram_frontend:latest
    platform: linux/amd64
    container_name: frontend
    volumes:
      - frontend_static:/app/build
    depends_on:
      - backend
    networks:
      - default

  gateway:
    image: b10nicle/kittygram_gateway:latest
    platform: linux/amd64
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - frontend_static:/var/html/static/
      - backend_static:/var/html/backend
      - media:/var/html/media
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - default

  postgres:
    image: postgres:13.10
    platform: linux/amd64
    container_name: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - default

volumes:
  frontend_static:
  backend_static:
  media:
  pgdata:
